name: Update DockerHub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  update-description:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@579f64ca0abced29dbbc44ab4c6a0b9e33ab3588 # v3.4.1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wildwildangel/dirb
          short-description: Alpine-based image to run dirb scanner
